services:
  mysql-db-videos:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_TCP_PORT: 3308
    ports:
    - 3308:3308
    expose:
      - 3308
    volumes:
      - mysql-data-videos:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  node-app-videos:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3002
      DB_HOST: mysql-db-videos
      DB_PORT: 3308
      DB_USER: root
      DB_NAME: mydatabase
      DB_PASSWORD: password
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      mysql-db-videos:
        condition: service_healthy
    networks:
      - mynetwork

volumes:
  mysql-data-videos:

networks:
  mynetwork:
    driver: bridge
